GET https://brainn-api-loterias.herokuapp.com/api/v1/loterias

###
GET https://brainn-api-loterias.herokuapp.com/api/v1/loterias-concursos

###
GET https://brainn-api-loterias.herokuapp.com/api/v1/concursos/5534


