export const megaColor = "#6befa3"
export const diaDeSorteColor = "#bfaf83"
export const lotoFacilColor = "#dd7ac6"
export const lotoManiaColor = "#ffab64"
export const quinaColor = "#8666ef"
export const timeManiaColor = "#5aad7d"